#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-odp-token-service.name" . }}-configmap
  labels: {{- include "eric-odp-token-service.labels" . | nindent 4 }}
  annotations: {{- include "eric-odp-token-service.annotations-with-prometheus" . | nindent 4 }}
data:
  sso_service_url: {{ .Values.sso_service.url | quote }}
  application.properties: |
    management.endpoint.metrics.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.web.server.auto-time-requests=true